project:
  type: website
  output-dir: docs

website:
  title: "Curiosior"
  navbar:
    right:
      - href: QUARTO.qmd
        text: Quarto
      - href: CURIOS.qmd
        text: Curiosities
      - about.qmd

  sidebar: 
    - id: quarto
      title: "Quarto"
      style: "docked"
      search: true
      contents: 
        - section: "Quarto"
          contents: 
            - auto: "QUARTO_LEC/*.qmd"

    - id: curiosities
      title: "Curiosities"
      style: "docked"
      search: true
      contents: 
        - section: "Curiosities"
          contents: 
            - auto: "CURIO/*.qmd"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

lang: ko




