project:
  type: website
  output-dir: docs

website:
  title: "Curiosior"
  navbar:
    right:
      - href: QUARTO.qmd
        text: Quarto
      - href: CURIOS.qmd
        text: Curiosities
      - about.qmd

  sidebar: 
    - id: quarto
      title: "Quarto"
      style: "docked"
      search: true
      contents: 
        - section: "Quarto"
          contents: 
            - auto: "QUARTO_LEC/**/*.qmd"

    - id: curiosities
      title: "Curiosities"
      style: "docked"
      search: true
      contents: 
        - section: "Curiosities"
          contents: 
            - auto: "CURIO/**/*.qmd"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    include-in-header: 
      text: '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">'

lang: ko



